name: Continuous Integration

on:
    pull_request:
        branches:
            - main

jobs:
    test: 
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: ['18', '20', '22']

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: forumapi_test

                options: >-
                    --health-cmd "pg_isready -U postgres"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}

            - name: Wait for PostgreSQL
              run: |
                for i in {1..10}; do
                  pg_isready -h localhost -p 5432 -U postgres && break
                  echo "Waiting for Postgres..."
                  sleep 5
                done

            - name: Install Dependencies
              run: npm install

            - name: Run Migrations
              run: npm run migrate:test
              env:
                PGHOST: localhost
                PGPORT: 5432
                PGUSER: developer
                PGPASSWORD: ${{ secrets.PGPASSWORD }}
                PGDATABASE: forumapi_test

            - name: Run Tests
              run: npm test
              env:
                CI: true
                HOST: localhost
                PORT: 5000
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}
                